<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Table\DataSource\Nopkey\_generated;

use Atlas\Table\TableEvents;

abstract class NopkeyTableEvents_ extends TableEvents
{
}
