<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Table\DataSource\Course\_generated;

use Atlas\Table\TableSelect;

/**
 * @method CourseRow|null fetchRow()
 * @method CourseRow[] fetchRows()
 */
abstract class CourseTableSelect_ extends TableSelect
{
}
